
function [ medians ] = train_median_filter( paths )
%   Detailed explanation goes here
%   Returns matrix of medians generated by getting the medians of files in
%   paths
    files = pullFiles(paths);
    
    [numFiles,~]=size(files);
    
    oneFileToGetSize = files{1};
    [rows,cols,colors]=size(oneFileToGetSize);
    
    pixelsOverTime = zeros(rows,cols,colors,numFiles);
    index = 1;
    for k = 1:length(files)
        file = files{k};
        J = file;
        pixelsOverTime(:,:,:,index) = J(:,:,:);
        index = index + 1;
    end
    
    medians = median(pixelsOverTime,4);
 
end

